import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@supabase/supabase-js";
import { assertAdminApi } from "@/lib/auth";
import { createSupabaseServerClient } from "@/lib/supabase/server";

const productSchema = z.object({ id: z.string().uuid().optional(), name: z.string().min(2), slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), sku: z.string().min(2), description: z.string().optional(), price: z.coerce.number().nonnegative(), sale_price: z.union([z.coerce.number().nonnegative(), z.literal(""), z.null()]).optional(), stock_quantity: z.coerce.number().int().nonnegative(), low_stock_threshold: z.coerce.number().int().nonnegative(), category_id: z.string().uuid().nullable().optional(), brand_id: z.string().uuid().nullable().optional(), tags: z.array(z.string()).default([]), is_published: z.boolean().default(false), is_featured: z.boolean().default(false), is_bestseller: z.boolean().default(false), seo_title: z.string().optional(), seo_description: z.string().optional() });

async function storageAdmin() { if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) return null; return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, { auth: { autoRefreshToken: false, persistSession: false } }); }
export async function GET() { const admin = await assertAdminApi(); if (!admin) return NextResponse.json({ error: "Unauthorized" }, { status: 403 }); const supabase = await createSupabaseServerClient(); const { data, error } = await supabase.from("products").select("*,categories(id,name,slug),brands(id,name,slug),product_images(id,storage_path,alt_text,sort_order)").order("created_at", { ascending: false }).limit(1000); return error ? NextResponse.json({ error: error.message }, { status: 400 }) : NextResponse.json({ products: data ?? [] }); }

export async function POST(request: Request) { const admin = await assertAdminApi(); if (!admin) return NextResponse.json({ error: "Unauthorized" }, { status: 403 }); const form = await request.formData(); const payload = productSchema.safeParse({ ...Object.fromEntries(Array.from(form.entries()).filter(([, value]) => typeof value === "string")), tags: String(form.get("tags") ?? "").split(",").map((tag) => tag.trim()).filter(Boolean), is_published: form.get("is_published") === "true", is_featured: form.get("is_featured") === "true", is_bestseller: form.get("is_bestseller") === "true", sale_price: form.get("sale_price") || null, category_id: form.get("category_id") || null, brand_id: form.get("brand_id") || null }); if (!payload.success) return NextResponse.json({ error: "Invalid product details", issues: payload.error.flatten() }, { status: 400 }); const supabase = await createSupabaseServerClient(); const { data: product, error } = await supabase.from("products").insert(payload.data).select("id").single(); if (error) return NextResponse.json({ error: error.message }, { status: 400 }); await uploadImages(product.id, form.getAll("images"), admin.user.id); return NextResponse.json({ product }); }

export async function PATCH(request: Request) { const admin = await assertAdminApi(); if (!admin) return NextResponse.json({ error: "Unauthorized" }, { status: 403 }); const parsed = productSchema.required({ id: true }).safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Invalid product details" }, { status: 400 }); const { id, ...changes } = parsed.data; const supabase = await createSupabaseServerClient(); const { error } = await supabase.from("products").update(changes).eq("id", id); return error ? NextResponse.json({ error: error.message }, { status: 400 }) : NextResponse.json({ ok: true }); }
export async function DELETE(request: Request) { const admin = await assertAdminApi(); if (!admin) return NextResponse.json({ error: "Unauthorized" }, { status: 403 }); const parsed = z.object({ id: z.string().uuid() }).safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Invalid product" }, { status: 400 }); const supabase = await createSupabaseServerClient(); const { error } = await supabase.from("products").delete().eq("id", parsed.data.id); return error ? NextResponse.json({ error: error.message }, { status: 400 }) : NextResponse.json({ ok: true }); }

async function uploadImages(productId: string, values: FormDataEntryValue[], userId: string) { const admin = await storageAdmin(); if (!admin) return; for (const value of values.filter((entry): entry is File => entry instanceof File && entry.size > 0).slice(0, 10)) { const path = `${productId}/${crypto.randomUUID()}-${value.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`; const upload = await admin.storage.from("product-images").upload(path, Buffer.from(await value.arrayBuffer()), { contentType: value.type, upsert: false }); if (!upload.error) await admin.from("product_images").insert({ product_id: productId, storage_path: path, alt_text: value.name, sort_order: 0 }); } await admin.from("admin_activity_logs").insert({ actor_id: userId, action: "product_images_uploaded", entity_type: "product", entity_id: productId }); }
