import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Cake, Clock3, Leaf, ShieldCheck, Star } from "lucide-react";
import { getHomeContent } from "@/lib/storefront";
import { ProductCard } from "@/components/storefront/product-card";
import { HeroCarousel } from "@/components/storefront/hero-carousel";

export default async function HomePage() {
  const { categories, featured, bestsellers, banners, reviews } = await getHomeContent();
  const signature = bestsellers.length ? bestsellers : featured;

  return <div>
    <HeroCarousel banners={banners} />

    <section className="container-shell py-16 md:py-24"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="eyebrow">From our counter to your table</p><h2 className="section-heading mt-3 max-w-xl">Find your kind of sweet.</h2></div><Link href="/shop" className="inline-flex items-center gap-2 text-sm font-extrabold text-navy hover:text-orange">Browse everything <ArrowRight size={16} /></Link></div><div className="mt-9 flex gap-4 overflow-x-auto pb-3 md:grid md:grid-cols-3 lg:grid-cols-6">{categories.length ? categories.map((category) => <Link key={category.slug} href={`/shop?category=${category.slug}`} className="group min-w-[150px] md:min-w-0"><div className="relative aspect-[.88] overflow-hidden rounded-2xl bg-cream-deep"><Image src={category.image} alt={category.name} fill sizes="(max-width: 768px) 150px, 18vw" className="object-cover transition-transform duration-700 group-hover:scale-105" /></div><h3 className="mt-3 text-sm font-extrabold text-navy group-hover:text-orange">{category.name}</h3><p className="mt-1 line-clamp-1 text-xs text-muted">{category.description ?? "Baked fresh today"}</p></Link>) : <div className="col-span-full border border-dashed border-line p-8 text-center text-sm text-muted">Categories will appear here once published in Admin.</div>}</div></section>

    <section className="border-y border-line bg-paper py-16 md:py-24"><div className="container-shell"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="eyebrow">Most loved this week</p><h2 className="section-heading mt-3">The ones people come back for.</h2></div><Link href="/shop" className="inline-flex items-center gap-2 text-sm font-extrabold text-navy hover:text-orange">Shop the menu <ArrowRight size={16} /></Link></div><div className="mt-10 grid grid-cols-2 gap-4 sm:gap-6 lg:grid-cols-4">{signature.length ? signature.slice(0, 4).map((product) => <ProductCard key={product.id} product={product} />) : <div className="col-span-full border border-dashed border-line p-10 text-center text-sm text-muted">Featured products will appear here once published in Admin.</div>}</div></div></section>

    <section className="container-shell py-16 md:py-24"><div className="grid overflow-hidden rounded-[24px] bg-navy md:grid-cols-[.92fr_1.08fr]"><div className="pattern-navy-dots flex flex-col justify-center p-8 text-white sm:p-12 lg:p-16"><p className="eyebrow text-orange">The Bake Mart cake studio</p><h2 className="mt-4 font-display text-4xl font-bold leading-tight sm:text-5xl">Your idea, finished in frosting.</h2><p className="mt-5 max-w-md text-sm leading-7 text-white/70">Tell us who you’re celebrating, share your inspiration and our cake artists will shape a bespoke creation around the moment.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/custom-cake" className="button-primary">Start a cake request <ArrowRight size={16} /></Link><Link href="/track-custom-cake" className="button-secondary border-white/25 bg-white/10 text-white hover:bg-white hover:text-navy">Track a request</Link></div></div><div className="relative min-h-[320px] md:min-h-[450px]"><Image src="https://images.unsplash.com/photo-1558301211-0d8c8ddee6ec?auto=format&fit=crop&w=1400&q=90" alt="A custom celebration cake" fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover" /></div></div></section>

    <section className="border-y border-line bg-cream-deep py-14 md:py-20"><div className="container-shell grid gap-8 md:grid-cols-3"><Promise icon={Clock3} title="Baked in small batches" copy="We make what we can serve at its best, every day." /><Promise icon={Leaf} title="Ingredients you can trust" copy="Real butter, fresh dairy and flavours worth coming back for." /><Promise icon={ShieldCheck} title="Delivered with care" copy="Your order is packed thoughtfully and brought to your door in Lahore." /></div></section>

    <section className="container-shell py-16 md:py-24"><div className="mx-auto max-w-2xl text-center"><p className="eyebrow">Notes from the table</p><h2 className="section-heading mt-3">Good words, shared generously.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{reviews.length ? reviews.map((review: any) => <article key={review.id} className="border border-line bg-white p-6" style={{ borderRadius: "var(--radius-card)" }}><div className="flex gap-1 text-orange">{Array.from({ length: review.rating }).map((_, index) => <Star key={index} size={14} fill="currentColor" />)}</div><p className="mt-5 font-display text-xl leading-relaxed text-navy">“{review.body}”</p><p className="mt-6 border-t border-line pt-4 text-xs font-extrabold text-muted">{review.profiles?.full_name ?? "Verified customer"}</p></article>) : <div className="col-span-full border border-dashed border-line p-10 text-center text-sm text-muted">Verified customer reviews will appear here after moderation.</div>}</div></section>

    <section className="container-shell pb-20"><div className="relative overflow-hidden rounded-[24px] bg-orange-light p-8 sm:p-12"><div className="pattern-dots absolute inset-0 opacity-70" /><div className="relative flex flex-col justify-between gap-7 md:flex-row md:items-center"><div><p className="eyebrow">A good place to begin</p><h2 className="mt-3 max-w-xl font-display text-3xl font-bold text-navy sm:text-4xl">Whether it’s a Tuesday treat or the big day, we’ve got something for it.</h2></div><Link href="/shop" className="button-primary shrink-0">Explore the bakery <ArrowRight size={16} /></Link></div></div></section>
  </div>;
}

function Promise({ icon: Icon, title, copy }: { icon: typeof Clock3; title: string; copy: string }) { return <div className="flex gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-white text-orange shadow-sm"><Icon size={21} /></span><div><h3 className="font-display text-xl font-bold text-navy">{title}</h3><p className="mt-1 text-sm leading-6 text-muted">{copy}</p></div></div>; }

export const dynamic = "force-dynamic";
